### Запустить жизненный цикл пользователя
GRPC localhost:50051/server.Customer/Create

{
  "name": "Джо Персиков",
  "phone": "79650843636"
}

> {%
    client.test("Checkout executed successfully", function() {
        client.assert(response.status === 207, `Status is ${response.status}`);
        client.assert(response.body.hasOwnProperty("id"), "Response does not contain identifier");
        client.assert(response.body.id.length > 0, "id is empty");
        client.global.set("customerId", response.body.id);
    });
%}

### Получить профиль
GRPC localhost:50051/server.Customer/Read

{
  "id": "{{ customerId }}"
}

### Обновить профиль
GRPC localhost:50051/server.Customer/Update

{
  "id": "{{ customerId }}",
  "name": "Джон Ананасов"
}

### Удалить профиль
GRPC localhost:50051/server.Customer/Delete

{
  "id": "{{ customerId }}"
}